# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [24]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

In [25]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'

df = pd.read_csv(url, sep = '\t')

### Step 3. Assign it to a variable called chipo.

In [ ]:
chipo = df

### Step 4. How many products cost more than $10.00?

In [26]:
 chipo['price_float']= pd.to_numeric(chipo.item_price.str.slice(1))

In [27]:
product_price = chipo.groupby('item_name').agg({'price_float': 'max'})

In [28]:
(product_price.price_float > 10).sum()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [32]:
product_price

                                       price_float
item_name
6 Pack Soft Drink                            12.98
Barbacoa Bowl                                11.75
Barbacoa Burrito                             11.75
Barbacoa Crispy Tacos                        18.50
Barbacoa Salad Bowl                          11.89
Barbacoa Soft Tacos                          11.75
Bottled Water                                15.00
Bowl                                         22.20
Burrito                                       7.40
Canned Soda                                   4.36
Canned Soft Drink                             5.00
Carnitas Bowl                                35.25
Carnitas Burrito                             18.50
Carnitas Crispy Tacos                        17.98
Carnitas Salad                                8.99
Carnitas Salad Bowl                          11.89
Carnitas Soft Tacos                          11.75
Chicken Bowl                                 32.94
Chicken Burrito                              35.00
Chicken Crispy Tacos                         17.50
Chicken Salad                                10.98
Chicken Salad Bowl                           22.50
Chicken Soft Tacos                           21.96
Chips                                         6.45
Chips and Fresh Tomato Salsa                 44.25
Chips and Guacamole                          17.80
Chips and Mild Fresh Tomato Salsa             3.00
Chips and Roasted Chili Corn Salsa            5.90
Chips and Roasted Chili-Corn Salsa            2.39
Chips and Tomatillo Green Chili Salsa         5.90
Chips and Tomatillo Red Chili Salsa           5.90
Chips and Tomatillo-Green Chili Salsa         4.78
Chips and Tomatillo-Red Chili Salsa           7.17
Crispy Tacos                                  7.40
Izze                                          3.39
Nantucket Nectar                              6.78
Salad                                         7.40
Side of Chips                                13.52
Steak Bowl                                   26.07
Steak Burrito                                27.75
Steak Crispy Tacos                           17.98
Steak Salad                                   8.99
Steak Salad Bowl                             23.78
Steak Soft Tacos                             18.50
Veggie Bowl                                  16.98
Veggie Burrito                               33.75
Veggie Crispy Tacos                           8.49
Veggie Salad                                  8.49
Veggie Salad Bowl                            11.25
Veggie Soft Tacos                            16.98

### Step 6. Sort by the name of the item

In [33]:
product_price.sort_index()

                                       price_float
item_name
6 Pack Soft Drink                            12.98
Barbacoa Bowl                                11.75
Barbacoa Burrito                             11.75
Barbacoa Crispy Tacos                        18.50
Barbacoa Salad Bowl                          11.89
Barbacoa Soft Tacos                          11.75
Bottled Water                                15.00
Bowl                                         22.20
Burrito                                       7.40
Canned Soda                                   4.36
Canned Soft Drink                             5.00
Carnitas Bowl                                35.25
Carnitas Burrito                             18.50
Carnitas Crispy Tacos                        17.98
Carnitas Salad                                8.99
Carnitas Salad Bowl                          11.89
Carnitas Soft Tacos                          11.75
Chicken Bowl                                 32.94
Chicken Burrito                              35.00
Chicken Crispy Tacos                         17.50
Chicken Salad                                10.98
Chicken Salad Bowl                           22.50
Chicken Soft Tacos                           21.96
Chips                                         6.45
Chips and Fresh Tomato Salsa                 44.25
Chips and Guacamole                          17.80
Chips and Mild Fresh Tomato Salsa             3.00
Chips and Roasted Chili Corn Salsa            5.90
Chips and Roasted Chili-Corn Salsa            2.39
Chips and Tomatillo Green Chili Salsa         5.90
Chips and Tomatillo Red Chili Salsa           5.90
Chips and Tomatillo-Green Chili Salsa         4.78
Chips and Tomatillo-Red Chili Salsa           7.17
Crispy Tacos                                  7.40
Izze                                          3.39
Nantucket Nectar                              6.78
Salad                                         7.40
Side of Chips                                13.52
Steak Bowl                                   26.07
Steak Burrito                                27.75
Steak Crispy Tacos                           17.98
Steak Salad                                   8.99
Steak Salad Bowl                             23.78
Steak Soft Tacos                             18.50
Veggie Bowl                                  16.98
Veggie Burrito                               33.75
Veggie Crispy Tacos                           8.49
Veggie Salad                                  8.49
Veggie Salad Bowl                            11.25
Veggie Soft Tacos                            16.98

### Step 7. What was the quantity of the most expensive item ordered?

In [34]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price,price float,price_float
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39,9.39,9.39

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [35]:
chipo[chipo.item_name == 'Veggie Salad Bowl'].quantity.sum()

18

### Step 9. How many times did someone order more than one Canned Soda?

In [36]:
(chipo[chipo.item_name == 'Canned Soda'].quantity > 1).sum()

20